'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/Poliza.xsd", IsNullable:=false)>  _
Partial Public Class Polizas
    
    Private polizaField() As PolizasPoliza
    
    Private versionField As String
    
    Private rFCField As String
    
    Private mesField As PolizasMes
    
    Private anoField As Integer
    
    Public Sub New()
        MyBase.New
        Me.versionField = "1.0"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Poliza")>  _
    Public Property Poliza() As PolizasPoliza()
        Get
            Return Me.polizaField
        End Get
        Set
            Me.polizaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Mes() As PolizasMes
        Get
            Return Me.mesField
        End Get
        Set
            Me.mesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Ano() As Integer
        Get
            Return Me.anoField
        End Get
        Set
            Me.anoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd")>  _
Partial Public Class PolizasPoliza
    
    Private transaccionField() As PolizasPolizaTransaccion
    
    Private tipoField As Integer
    
    Private numField As String
    
    Private fechaField As Date
    
    Private conceptoField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Transaccion")>  _
    Public Property Transaccion() As PolizasPolizaTransaccion()
        Get
            Return Me.transaccionField
        End Get
        Set
            Me.transaccionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Tipo() As Integer
        Get
            Return Me.tipoField
        End Get
        Set
            Me.tipoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Num() As String
        Get
            Return Me.numField
        End Get
        Set
            Me.numField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Concepto() As String
        Get
            Return Me.conceptoField
        End Get
        Set
            Me.conceptoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd")>  _
Partial Public Class PolizasPolizaTransaccion
    
    Private chequeField() As PolizasPolizaTransaccionCheque
    
    Private transferenciaField() As PolizasPolizaTransaccionTransferencia
    
    Private comprobantesField() As PolizasPolizaTransaccionComprobantes
    
    Private numCtaField As String
    
    Private conceptoField As String
    
    Private debeField As Decimal
    
    Private haberField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cheque")>  _
    Public Property Cheque() As PolizasPolizaTransaccionCheque()
        Get
            Return Me.chequeField
        End Get
        Set
            Me.chequeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Transferencia")>  _
    Public Property Transferencia() As PolizasPolizaTransaccionTransferencia()
        Get
            Return Me.transferenciaField
        End Get
        Set
            Me.transferenciaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Comprobantes")>  _
    Public Property Comprobantes() As PolizasPolizaTransaccionComprobantes()
        Get
            Return Me.comprobantesField
        End Get
        Set
            Me.comprobantesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumCta() As String
        Get
            Return Me.numCtaField
        End Get
        Set
            Me.numCtaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Concepto() As String
        Get
            Return Me.conceptoField
        End Get
        Set
            Me.conceptoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Debe() As Decimal
        Get
            Return Me.debeField
        End Get
        Set
            Me.debeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Haber() As Decimal
        Get
            Return Me.haberField
        End Get
        Set
            Me.haberField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd")>  _
Partial Public Class PolizasPolizaTransaccionCheque
    
    Private numField As String
    
    Private bancoField As String
    
    Private ctaOriField As String
    
    Private fechaField As Date
    
    Private montoField As Decimal
    
    Private benefField As String
    
    Private rFCField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Num() As String
        Get
            Return Me.numField
        End Get
        Set
            Me.numField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Banco() As String
        Get
            Return Me.bancoField
        End Get
        Set
            Me.bancoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaOri() As String
        Get
            Return Me.ctaOriField
        End Get
        Set
            Me.ctaOriField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Benef() As String
        Get
            Return Me.benefField
        End Get
        Set
            Me.benefField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd")>  _
Partial Public Class PolizasPolizaTransaccionTransferencia
    
    Private ctaOriField As String
    
    Private bancoOriField As String
    
    Private montoField As Decimal
    
    Private ctaDestField As String
    
    Private bancoDestField As String
    
    Private fechaField As Date
    
    Private benefField As String
    
    Private rFCField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaOri() As String
        Get
            Return Me.ctaOriField
        End Get
        Set
            Me.ctaOriField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BancoOri() As String
        Get
            Return Me.bancoOriField
        End Get
        Set
            Me.bancoOriField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaDest() As String
        Get
            Return Me.ctaDestField
        End Get
        Set
            Me.ctaDestField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BancoDest() As String
        Get
            Return Me.bancoDestField
        End Get
        Set
            Me.bancoDestField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Benef() As String
        Get
            Return Me.benefField
        End Get
        Set
            Me.benefField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd")>  _
Partial Public Class PolizasPolizaTransaccionComprobantes
    
    Private uUID_CFDIField As String
    
    Private montoField As Decimal
    
    Private rFCField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property UUID_CFDI() As String
        Get
            Return Me.uUID_CFDIField
        End Get
        Set
            Me.uUID_CFDIField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/Poliza.xsd")>  _
Public Enum PolizasMes
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("01")>  _
    Item01
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("02")>  _
    Item02
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("03")>  _
    Item03
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("04")>  _
    Item04
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("05")>  _
    Item05
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("06")>  _
    Item06
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("07")>  _
    Item07
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("08")>  _
    Item08
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("09")>  _
    Item09
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("10")>  _
    Item10
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("11")>  _
    Item11
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("12")>  _
    Item12
End Enum
