'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CargarDatos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", ConfigurationName:="CargarDatos.WSCargaDatosSoap")>  _
    Public Interface WSCargaDatosSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ScheduleResult del espacio de nombres http://localhost/GoVirtual/WsVDealer/WsCargaDatos no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos/Schedule", ReplyAction:="*")>  _
        Function Schedule(ByVal request As CargarDatos.ScheduleRequest) As CargarDatos.ScheduleResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://localhost/GoVirtual/WsVDealer/WsCargaDatos no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos/CompruebaConexion", ReplyAction:="*")>  _
        Function CompruebaConexion(ByVal request As CargarDatos.CompruebaConexionRequest) As CargarDatos.CompruebaConexionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://localhost/GoVirtual/WsVDealer/WsCargaDatos no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos/SendDatos", ReplyAction:="*")>  _
        Function SendDatos(ByVal request As CargarDatos.SendDatosRequest) As CargarDatos.SendDatosResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://localhost/GoVirtual/WsVDealer/WsCargaDatos no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos/ComprobarCargaEAT", ReplyAction:="*")>  _
        Function ComprobarCargaEAT(ByVal request As CargarDatos.ComprobarCargaEATRequest) As CargarDatos.ComprobarCargaEATResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://localhost/GoVirtual/WsVDealer/WsCargaDatos no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos/EjecutaSQLEAT", ReplyAction:="*")>  _
        Function EjecutaSQLEAT(ByVal request As CargarDatos.EjecutaSQLEATRequest) As CargarDatos.EjecutaSQLEATResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ScheduleRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Schedule", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.ScheduleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.ScheduleRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class ScheduleRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public razonsocial As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public distribuidor As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public fecha As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal razonsocial As Integer, ByVal distribuidor As Integer, ByVal fecha As Date)
            MyBase.New
            Me.razonsocial = razonsocial
            Me.distribuidor = distribuidor
            Me.fecha = fecha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ScheduleResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ScheduleResponse", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.ScheduleResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.ScheduleResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class ScheduleResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ScheduleResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ScheduleResult As String)
            MyBase.New
            Me.ScheduleResult = ScheduleResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompruebaConexionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompruebaConexion", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.CompruebaConexionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.CompruebaConexionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class CompruebaConexionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public distribuidor As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public fecha As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal distribuidor As Integer, ByVal fecha As String)
            MyBase.New
            Me.distribuidor = distribuidor
            Me.fecha = fecha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompruebaConexionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompruebaConexionResponse", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.CompruebaConexionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.CompruebaConexionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class CompruebaConexionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CompruebaConexionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CompruebaConexionResult As String)
            MyBase.New
            Me.CompruebaConexionResult = CompruebaConexionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendDatosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendDatos", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.SendDatosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.SendDatosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class SendDatosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public distribuidor As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public FechaTraslado As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public XML() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal distribuidor As Integer, ByVal FechaTraslado As String, ByVal XML() As Byte)
            MyBase.New
            Me.usuario = usuario
            Me.distribuidor = distribuidor
            Me.FechaTraslado = FechaTraslado
            Me.XML = XML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendDatosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendDatosResponse", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.SendDatosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.SendDatosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class SendDatosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendDatosResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendDatosResult As String)
            MyBase.New
            Me.SendDatosResult = SendDatosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ComprobarCargaEATRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ComprobarCargaEAT", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.ComprobarCargaEATRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.ComprobarCargaEATRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class ComprobarCargaEATRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public distribuidor As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public FechaTraslado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal distribuidor As Integer, ByVal FechaTraslado As String)
            MyBase.New
            Me.usuario = usuario
            Me.distribuidor = distribuidor
            Me.FechaTraslado = FechaTraslado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ComprobarCargaEATResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ComprobarCargaEATResponse", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.ComprobarCargaEATResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.ComprobarCargaEATResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class ComprobarCargaEATResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ComprobarCargaEATResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ComprobarCargaEATResult As String)
            MyBase.New
            Me.ComprobarCargaEATResult = ComprobarCargaEATResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EjecutaSQLEATRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EjecutaSQLEAT", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.EjecutaSQLEATRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.EjecutaSQLEATRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class EjecutaSQLEATRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public distribuidor As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public FechaTraslado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal distribuidor As Integer, ByVal FechaTraslado As String)
            MyBase.New
            Me.usuario = usuario
            Me.distribuidor = distribuidor
            Me.FechaTraslado = FechaTraslado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EjecutaSQLEATResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EjecutaSQLEATResponse", [Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos", Order:=0)>  _
        Public Body As CargarDatos.EjecutaSQLEATResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CargarDatos.EjecutaSQLEATResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/GoVirtual/WsVDealer/WsCargaDatos")>  _
    Partial Public Class EjecutaSQLEATResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EjecutaSQLEATResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EjecutaSQLEATResult As String)
            MyBase.New
            Me.EjecutaSQLEATResult = EjecutaSQLEATResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSCargaDatosSoapChannel
        Inherits CargarDatos.WSCargaDatosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSCargaDatosSoapClient
        Inherits System.ServiceModel.ClientBase(Of CargarDatos.WSCargaDatosSoap)
        Implements CargarDatos.WSCargaDatosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CargarDatos_WSCargaDatosSoap_Schedule(ByVal request As CargarDatos.ScheduleRequest) As CargarDatos.ScheduleResponse Implements CargarDatos.WSCargaDatosSoap.Schedule
            Return MyBase.Channel.Schedule(request)
        End Function
        
        Public Function Schedule(ByVal razonsocial As Integer, ByVal distribuidor As Integer, ByVal fecha As Date) As String
            Dim inValue As CargarDatos.ScheduleRequest = New CargarDatos.ScheduleRequest()
            inValue.Body = New CargarDatos.ScheduleRequestBody()
            inValue.Body.razonsocial = razonsocial
            inValue.Body.distribuidor = distribuidor
            inValue.Body.fecha = fecha
            Dim retVal As CargarDatos.ScheduleResponse = CType(Me,CargarDatos.WSCargaDatosSoap).Schedule(inValue)
            Return retVal.Body.ScheduleResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CargarDatos_WSCargaDatosSoap_CompruebaConexion(ByVal request As CargarDatos.CompruebaConexionRequest) As CargarDatos.CompruebaConexionResponse Implements CargarDatos.WSCargaDatosSoap.CompruebaConexion
            Return MyBase.Channel.CompruebaConexion(request)
        End Function
        
        Public Function CompruebaConexion(ByVal distribuidor As Integer, ByVal fecha As String) As String
            Dim inValue As CargarDatos.CompruebaConexionRequest = New CargarDatos.CompruebaConexionRequest()
            inValue.Body = New CargarDatos.CompruebaConexionRequestBody()
            inValue.Body.distribuidor = distribuidor
            inValue.Body.fecha = fecha
            Dim retVal As CargarDatos.CompruebaConexionResponse = CType(Me,CargarDatos.WSCargaDatosSoap).CompruebaConexion(inValue)
            Return retVal.Body.CompruebaConexionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CargarDatos_WSCargaDatosSoap_SendDatos(ByVal request As CargarDatos.SendDatosRequest) As CargarDatos.SendDatosResponse Implements CargarDatos.WSCargaDatosSoap.SendDatos
            Return MyBase.Channel.SendDatos(request)
        End Function
        
        Public Function SendDatos(ByVal usuario As String, ByVal distribuidor As Integer, ByVal FechaTraslado As String, ByVal XML() As Byte) As String
            Dim inValue As CargarDatos.SendDatosRequest = New CargarDatos.SendDatosRequest()
            inValue.Body = New CargarDatos.SendDatosRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.distribuidor = distribuidor
            inValue.Body.FechaTraslado = FechaTraslado
            inValue.Body.XML = XML
            Dim retVal As CargarDatos.SendDatosResponse = CType(Me,CargarDatos.WSCargaDatosSoap).SendDatos(inValue)
            Return retVal.Body.SendDatosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CargarDatos_WSCargaDatosSoap_ComprobarCargaEAT(ByVal request As CargarDatos.ComprobarCargaEATRequest) As CargarDatos.ComprobarCargaEATResponse Implements CargarDatos.WSCargaDatosSoap.ComprobarCargaEAT
            Return MyBase.Channel.ComprobarCargaEAT(request)
        End Function
        
        Public Function ComprobarCargaEAT(ByVal usuario As String, ByVal distribuidor As Integer, ByVal FechaTraslado As String) As String
            Dim inValue As CargarDatos.ComprobarCargaEATRequest = New CargarDatos.ComprobarCargaEATRequest()
            inValue.Body = New CargarDatos.ComprobarCargaEATRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.distribuidor = distribuidor
            inValue.Body.FechaTraslado = FechaTraslado
            Dim retVal As CargarDatos.ComprobarCargaEATResponse = CType(Me,CargarDatos.WSCargaDatosSoap).ComprobarCargaEAT(inValue)
            Return retVal.Body.ComprobarCargaEATResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CargarDatos_WSCargaDatosSoap_EjecutaSQLEAT(ByVal request As CargarDatos.EjecutaSQLEATRequest) As CargarDatos.EjecutaSQLEATResponse Implements CargarDatos.WSCargaDatosSoap.EjecutaSQLEAT
            Return MyBase.Channel.EjecutaSQLEAT(request)
        End Function
        
        Public Function EjecutaSQLEAT(ByVal usuario As String, ByVal distribuidor As Integer, ByVal FechaTraslado As String) As String
            Dim inValue As CargarDatos.EjecutaSQLEATRequest = New CargarDatos.EjecutaSQLEATRequest()
            inValue.Body = New CargarDatos.EjecutaSQLEATRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.distribuidor = distribuidor
            inValue.Body.FechaTraslado = FechaTraslado
            Dim retVal As CargarDatos.EjecutaSQLEATResponse = CType(Me,CargarDatos.WSCargaDatosSoap).EjecutaSQLEAT(inValue)
            Return retVal.Body.EjecutaSQLEATResult
        End Function
    End Class
End Namespace
