'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas"), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas", IsNullable:=False)> _
Partial Public Class AuxiliarCtas

    <System.Xml.Serialization.XmlAttributeAttribute(AttributeName:="schemaLocation", Namespace:="http://www.w3.org/2001/XMLSchema-instance")> _
    Public schemaLocation As String = "www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas " + "http://www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas/AuxiliarCtas_1_1.xsd"

    Private cuentaField() As AuxiliarCtasCuenta

    Private versionField As String

    Private rFCField As String

    Private mesField As String

    Private anioField As Integer

    Private tipoSolicitudField As String

    Private numOrdenField As String

    Private numTramiteField As String

    Private selloField As String

    Private noCertificadoField As String

    Private certificadoField As String

    Public Sub New()
        MyBase.New()
        Me.versionField = "1.1"
    End Sub

    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Cuenta")> _
    Public Property Cuenta() As AuxiliarCtasCuenta()
        Get
            Return Me.cuentaField
        End Get
        Set(ByVal value As AuxiliarCtasCuenta())
            Me.cuentaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set(ByVal value As String)
            Me.versionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set(ByVal value As String)
            Me.rFCField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Mes() As String
        Get
            Return Me.mesField
        End Get
        Set(ByVal value As String)
            Me.mesField = value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Anio() As Integer
        Get
            Return Me.anioField
        End Get
        Set(ByVal value As Integer)
            Me.anioField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property TipoSolicitud() As String
        Get
            Return Me.tipoSolicitudField
        End Get
        Set(ByVal value As String)
            Me.tipoSolicitudField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property NumOrden() As String
        Get
            Return Me.numOrdenField
        End Get
        Set(ByVal value As String)
            Me.numOrdenField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property NumTramite() As String
        Get
            Return Me.numTramiteField
        End Get
        Set(ByVal value As String)
            Me.numTramiteField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Sello() As String
        Get
            Return Me.selloField
        End Get
        Set(ByVal value As String)
            Me.selloField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property noCertificado() As String
        Get
            Return Me.noCertificadoField
        End Get
        Set(ByVal value As String)
            Me.noCertificadoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Certificado() As String
        Get
            Return Me.certificadoField
        End Get
        Set(ByVal value As String)
            Me.certificadoField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas")>  _
Partial Public Class AuxiliarCtasCuenta
    
    Private detalleAuxField() As AuxiliarCtasCuentaDetalleAux
    
    Private numCtaField As String
    
    Private desCtaField As String
    
    Private saldoIniField As Decimal
    
    Private saldoFinField As Decimal
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("DetalleAux")>  _
    Public Property DetalleAux() As AuxiliarCtasCuentaDetalleAux()
        Get
            Return Me.detalleAuxField
        End Get
        Set
            Me.detalleAuxField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumCta() As String
        Get
            Return Me.numCtaField
        End Get
        Set
            Me.numCtaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property DesCta() As String
        Get
            Return Me.desCtaField
        End Get
        Set
            Me.desCtaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SaldoIni() As Decimal
        Get
            Return Me.saldoIniField
        End Get
        Set
            Me.saldoIniField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SaldoFin() As Decimal
        Get
            Return Me.saldoFinField
        End Get
        Set
            Me.saldoFinField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas")>  _
Partial Public Class AuxiliarCtasCuentaDetalleAux
    
    Private fechaField As String
    
    Private numUnIdenPolField As String
    
    Private conceptoField As String
    
    Private debeField As Decimal
    
    Private haberField As Decimal
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Fecha() As String
        Get
            Return Me.fechaField
        End Get
        Set(ByVal value As String)
            Me.fechaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumUnIdenPol() As String
        Get
            Return Me.numUnIdenPolField
        End Get
        Set
            Me.numUnIdenPolField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Concepto() As String
        Get
            Return Me.conceptoField
        End Get
        Set
            Me.conceptoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Debe() As Decimal
        Get
            Return Me.debeField
        End Get
        Set
            Me.debeField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Haber() As Decimal
        Get
            Return Me.haberField
        End Get
        Set
            Me.haberField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/AuxiliarCtas")>  _
Public Enum AuxiliarCtasMes
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("01")>  _
    Item01
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("02")>  _
    Item02
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("03")>  _
    Item03
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("04")>  _
    Item04
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("05")>  _
    Item05
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("06")>  _
    Item06
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("07")>  _
    Item07
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("08")>  _
    Item08
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("09")>  _
    Item09
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("10")>  _
    Item10
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("11")>  _
    Item11
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("12")>  _
    Item12
End Enum
