'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion", IsNullable:=false)>  _
Partial Public Class Balanza

    <System.Xml.Serialization.XmlAttributeAttribute(AttributeName:="schemaLocation", Namespace:="http://www.w3.org/2001/XMLSchema-instance")> _
    Public schemaLocation As String = "www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion " + "http://www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion/BalanzaComprobacion_1_1.xsd"

    Private ctasField() As BalanzaCtas
    
    Private versionField As String
    
    Private rFCField As String
    
    Private mesField As String
    
    Private anioField As Integer
    
    Private tipoEnvioField As String
    
    Private fechaModBalField As String
    
    Private fechaModBalFieldSpecified As Boolean
    
    Private selloField As String
    
    Private noCertificadoField As String
    
    Private certificadoField As String
    
    Public Sub New()
        MyBase.New
        Me.versionField = "1.1"
    End Sub
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Ctas")>  _
    Public Property Ctas() As BalanzaCtas()
        Get
            Return Me.ctasField
        End Get
        Set
            Me.ctasField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Mes() As String
        Get
            Return Me.mesField
        End Get
        Set(ByVal value As String)
            Me.mesField = Value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Anio() As Integer
        Get
            Return Me.anioField
        End Get
        Set
            Me.anioField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoEnvio() As String
        Get
            Return Me.tipoEnvioField
        End Get
        Set
            Me.tipoEnvioField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property FechaModBal() As String
        Get
            Return Me.fechaModBalField
        End Get
        Set(ByVal value As String)
            Me.fechaModBalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property FechaModBalSpecified() As Boolean
        Get
            Return Me.fechaModBalFieldSpecified
        End Get
        Set
            Me.fechaModBalFieldSpecified = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Sello() As String
        Get
            Return Me.selloField
        End Get
        Set
            Me.selloField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noCertificado() As String
        Get
            Return Me.noCertificadoField
        End Get
        Set
            Me.noCertificadoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Certificado() As String
        Get
            Return Me.certificadoField
        End Get
        Set
            Me.certificadoField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion")>  _
Partial Public Class BalanzaCtas
    
    Private numCtaField As String
    
    Private saldoIniField As Decimal
    
    Private debeField As Decimal
    
    Private haberField As Decimal
    
    Private saldoFinField As Decimal
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumCta() As String
        Get
            Return Me.numCtaField
        End Get
        Set
            Me.numCtaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SaldoIni() As Decimal
        Get
            Return Me.saldoIniField
        End Get
        Set
            Me.saldoIniField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Debe() As Decimal
        Get
            Return Me.debeField
        End Get
        Set
            Me.debeField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Haber() As Decimal
        Get
            Return Me.haberField
        End Get
        Set
            Me.haberField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SaldoFin() As Decimal
        Get
            Return Me.saldoFinField
        End Get
        Set
            Me.saldoFinField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion")>  _
Public Enum BalanzaMes
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("01")>  _
    Item01
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("02")>  _
    Item02
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("03")>  _
    Item03
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("04")>  _
    Item04
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("05")>  _
    Item05
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("06")>  _
    Item06
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("07")>  _
    Item07
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("08")>  _
    Item08
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("09")>  _
    Item09
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("10")>  _
    Item10
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("11")>  _
    Item11
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("12")>  _
    Item12
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("13")>  _
    Item13
End Enum
