'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo", IsNullable:=false)>  _
Partial Public Class Polizas

    <System.Xml.Serialization.XmlAttributeAttribute(AttributeName:="schemaLocation", Namespace:="http://www.w3.org/2001/XMLSchema-instance")> _
    Public schemaLocation As String = "www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo " + "http://www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo/PolizasPeriodo_1_1.xsd"


    Private polizaField() As PolizasPoliza
    
    Private versionField As String
    
    Private rFCField As String
    
    Private mesField As String
    
    Private anioField As Integer
    
    Private tipoSolicitudField As String
    
    Private numOrdenField As String
    
    Private numTramiteField As String
    
    Private selloField As String
    
    Private noCertificadoField As String
    
    Private certificadoField As String
    
    Public Sub New()
        MyBase.New
        Me.versionField = "1.1"
    End Sub
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Poliza")>  _
    Public Property Poliza() As PolizasPoliza()
        Get
            Return Me.polizaField
        End Get
        Set
            Me.polizaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Mes() As String
        Get
            Return Me.mesField
        End Get
        Set(ByVal value As String)
            Me.mesField = Value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Anio() As Integer
        Get
            Return Me.anioField
        End Get
        Set
            Me.anioField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoSolicitud() As String
        Get
            Return Me.tipoSolicitudField
        End Get
        Set
            Me.tipoSolicitudField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumOrden() As String
        Get
            Return Me.numOrdenField
        End Get
        Set
            Me.numOrdenField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumTramite() As String
        Get
            Return Me.numTramiteField
        End Get
        Set
            Me.numTramiteField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Sello() As String
        Get
            Return Me.selloField
        End Get
        Set
            Me.selloField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noCertificado() As String
        Get
            Return Me.noCertificadoField
        End Get
        Set
            Me.noCertificadoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Certificado() As String
        Get
            Return Me.certificadoField
        End Get
        Set
            Me.certificadoField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPoliza
    
    Private transaccionField() As PolizasPolizaTransaccion
    
    Private numUnIdenPolField As String
    
    Private fechaField As String
    
    Private conceptoField As String
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Transaccion")>  _
    Public Property Transaccion() As PolizasPolizaTransaccion()
        Get
            Return Me.transaccionField
        End Get
        Set
            Me.transaccionField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumUnIdenPol() As String
        Get
            Return Me.numUnIdenPolField
        End Get
        Set
            Me.numUnIdenPolField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Fecha() As String
        Get
            Return Me.fechaField
        End Get
        Set(ByVal value As String)
            Me.fechaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Concepto() As String
        Get
            Return Me.conceptoField
        End Get
        Set
            Me.conceptoField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccion
    
    Private compNalField() As PolizasPolizaTransaccionCompNal
    
    Private compNalOtrField() As PolizasPolizaTransaccionCompNalOtr
    
    Private compExtField() As PolizasPolizaTransaccionCompExt
    
    Private chequeField() As PolizasPolizaTransaccionCheque
    
    Private transferenciaField() As PolizasPolizaTransaccionTransferencia
    
    Private otrMetodoPagoField() As PolizasPolizaTransaccionOtrMetodoPago
    
    Private numCtaField As String
    
    Private desCtaField As String
    
    Private conceptoField As String
    
    Private debeField As Decimal
    
    Private haberField As Decimal
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("CompNal")>  _
    Public Property CompNal() As PolizasPolizaTransaccionCompNal()
        Get
            Return Me.compNalField
        End Get
        Set
            Me.compNalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("CompNalOtr")>  _
    Public Property CompNalOtr() As PolizasPolizaTransaccionCompNalOtr()
        Get
            Return Me.compNalOtrField
        End Get
        Set
            Me.compNalOtrField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("CompExt")>  _
    Public Property CompExt() As PolizasPolizaTransaccionCompExt()
        Get
            Return Me.compExtField
        End Get
        Set
            Me.compExtField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Cheque")>  _
    Public Property Cheque() As PolizasPolizaTransaccionCheque()
        Get
            Return Me.chequeField
        End Get
        Set
            Me.chequeField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Transferencia")>  _
    Public Property Transferencia() As PolizasPolizaTransaccionTransferencia()
        Get
            Return Me.transferenciaField
        End Get
        Set
            Me.transferenciaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("OtrMetodoPago")>  _
    Public Property OtrMetodoPago() As PolizasPolizaTransaccionOtrMetodoPago()
        Get
            Return Me.otrMetodoPagoField
        End Get
        Set
            Me.otrMetodoPagoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumCta() As String
        Get
            Return Me.numCtaField
        End Get
        Set
            Me.numCtaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property DesCta() As String
        Get
            Return Me.desCtaField
        End Get
        Set
            Me.desCtaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Concepto() As String
        Get
            Return Me.conceptoField
        End Get
        Set
            Me.conceptoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Debe() As Decimal
        Get
            Return Me.debeField
        End Get
        Set
            Me.debeField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Haber() As Decimal
        Get
            Return Me.haberField
        End Get
        Set
            Me.haberField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccionCompNal
    
    Private uUID_CFDIField As String
    
    Private rFCField As String
    
    Private montoTotalField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property UUID_CFDI() As String
        Get
            Return Me.uUID_CFDIField
        End Get
        Set
            Me.uUID_CFDIField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property MontoTotal() As Decimal
        Get
            Return Me.montoTotalField
        End Get
        Set
            Me.montoTotalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccionCompNalOtr
    
    Private cFD_CBB_SerieField As String
    
    Private cFD_CBB_NumFolField As String
    
    Private rFCField As String
    
    Private montoTotalField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CFD_CBB_Serie() As String
        Get
            Return Me.cFD_CBB_SerieField
        End Get
        Set
            Me.cFD_CBB_SerieField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
    Public Property CFD_CBB_NumFol() As String
        Get
            Return Me.cFD_CBB_NumFolField
        End Get
        Set
            Me.cFD_CBB_NumFolField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property MontoTotal() As Decimal
        Get
            Return Me.montoTotalField
        End Get
        Set
            Me.montoTotalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccionCompExt
    
    Private numFactExtField As String
    
    Private taxIDField As String
    
    Private montoTotalField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumFactExt() As String
        Get
            Return Me.numFactExtField
        End Get
        Set
            Me.numFactExtField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TaxID() As String
        Get
            Return Me.taxIDField
        End Get
        Set
            Me.taxIDField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property MontoTotal() As Decimal
        Get
            Return Me.montoTotalField
        End Get
        Set
            Me.montoTotalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccionCheque
    
    Private numField As String
    
    Private banEmisNalField As String
    
    Private banEmisExtField As String
    
    Private ctaOriField As String
    
    Private fechaField As Date
    
    Private benefField As String
    
    Private rFCField As String
    
    Private montoField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Num() As String
        Get
            Return Me.numField
        End Get
        Set
            Me.numField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BanEmisNal() As String
        Get
            Return Me.banEmisNalField
        End Get
        Set
            Me.banEmisNalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BanEmisExt() As String
        Get
            Return Me.banEmisExtField
        End Get
        Set
            Me.banEmisExtField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaOri() As String
        Get
            Return Me.ctaOriField
        End Get
        Set
            Me.ctaOriField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Benef() As String
        Get
            Return Me.benefField
        End Get
        Set
            Me.benefField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccionTransferencia
    
    Private ctaOriField As String
    
    Private bancoOriNalField As String
    
    Private bancoOriExtField As String
    
    Private ctaDestField As String
    
    Private bancoDestNalField As String
    
    Private bancoDestExtField As String
    
    Private fechaField As Date
    
    Private benefField As String
    
    Private rFCField As String
    
    Private montoField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaOri() As String
        Get
            Return Me.ctaOriField
        End Get
        Set
            Me.ctaOriField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BancoOriNal() As String
        Get
            Return Me.bancoOriNalField
        End Get
        Set
            Me.bancoOriNalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BancoOriExt() As String
        Get
            Return Me.bancoOriExtField
        End Get
        Set
            Me.bancoOriExtField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaDest() As String
        Get
            Return Me.ctaDestField
        End Get
        Set
            Me.ctaDestField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BancoDestNal() As String
        Get
            Return Me.bancoDestNalField
        End Get
        Set
            Me.bancoDestNalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property BancoDestExt() As String
        Get
            Return Me.bancoDestExtField
        End Get
        Set
            Me.bancoDestExtField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Benef() As String
        Get
            Return Me.benefField
        End Get
        Set
            Me.benefField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Partial Public Class PolizasPolizaTransaccionOtrMetodoPago
    
    Private metPagoPolField As String
    
    Private fechaField As Date
    
    Private benefField As String
    
    Private rFCField As String
    
    Private montoField As Decimal
    
    Private monedaField As String
    
    Private tipCambField As Decimal
    
    Private tipCambFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property MetPagoPol() As String
        Get
            Return Me.metPagoPolField
        End Get
        Set
            Me.metPagoPolField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Benef() As String
        Get
            Return Me.benefField
        End Get
        Set
            Me.benefField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RFC() As String
        Get
            Return Me.rFCField
        End Get
        Set
            Me.rFCField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipCamb() As Decimal
        Get
            Return Me.tipCambField
        End Get
        Set
            Me.tipCambField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipCambSpecified() As Boolean
        Get
            Return Me.tipCambFieldSpecified
        End Get
        Set
            Me.tipCambFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="www.sat.gob.mx/esquemas/ContabilidadE/1_1/PolizasPeriodo")>  _
Public Enum PolizasMes
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("01")>  _
    Item01
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("02")>  _
    Item02
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("03")>  _
    Item03
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("04")>  _
    Item04
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("05")>  _
    Item05
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("06")>  _
    Item06
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("07")>  _
    Item07
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("08")>  _
    Item08
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("09")>  _
    Item09
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("10")>  _
    Item10
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("11")>  _
    Item11
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("12")>  _
    Item12
End Enum
