'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital", IsNullable:=false)>  _
Partial Public Class TimbreFiscalDigital
    
    Private versionField As String
    
    Private uUIDField As String
    
    Private fechaTimbradoField As Date
    
    Private selloCFDField As String
    
    Private noCertificadoSATField As String
    
    Private selloSATField As String
    
    Public Sub New()
        MyBase.New
        Me.versionField = "1.0"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property UUID() As String
        Get
            Return Me.uUIDField
        End Get
        Set
            Me.uUIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property FechaTimbrado() As Date
        Get
            Return Me.fechaTimbradoField
        End Get
        Set
            Me.fechaTimbradoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property selloCFD() As String
        Get
            Return Me.selloCFDField
        End Get
        Set
            Me.selloCFDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noCertificadoSAT() As String
        Get
            Return Me.noCertificadoSATField
        End Get
        Set
            Me.noCertificadoSATField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property selloSAT() As String
        Get
            Return Me.selloSATField
        End Get
        Set
            Me.selloSATField = value
        End Set
    End Property
End Class
